DROP TABLE IF EXISTS `MEETING_TABLE`;

CREATE TABLE `MEETING_TABLE` (
  `meetingId` int(11) NOT NULL ,
  `name` varchar(45) DEFAULT NULL,
  `description` varchar(200) DEFAULT NULL,
  `department` int(11) DEFAULT NULL,
  PRIMARY KEY (`meetingId`),
  KEY `fk_MEETING_TABLE_1_idx` (`department`),
  CONSTRAINT `fk_MEETING_TABLE_1` FOREIGN KEY (`department`) REFERENCES `DEPARTMENT_TABLE` (`departmentId`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

LOCK TABLES `MEETING_TABLE` WRITE;

UNLOCK TABLES;
