DROP TABLE IF EXISTS `EMPLOYEE_TABLE`;

CREATE TABLE `EMPLOYEE_TABLE` (
  `employeeId` int(11) NOT NULL ,
  `name` varchar(45) DEFAULT NULL,
  `surname` varchar(45) DEFAULT NULL,
  `salary` double DEFAULT NULL,
  `department` int(11) DEFAULT NULL,
  KEY `fk_EMPLOYEE_TABLE_1_idx` (`department`),
  CONSTRAINT `fk_EMPLOYEE_TABLE_1` FOREIGN KEY (`department`) REFERENCES `DEPARTMENT_TABLE` (`departmentId`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


LOCK TABLES `EMPLOYEE_TABLE` WRITE;

UNLOCK TABLES;