DROP TABLE IF EXISTS `DEPARTMENT_TABLE`;

CREATE TABLE `DEPARTMENT_TABLE` (
  `departmentId` int(11) NOT NULL,
  `name` varchar(45) DEFAULT NULL,
  `description` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`departmentId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

LOCK TABLES `DEPARTMENT_TABLE` WRITE;

UNLOCK TABLES;
